apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: nginx-deploy
  template:
    metadata:
      labels:
	tier: nginx-deploy
    spec:
      containers:
      - name: nginx-cont
        image: nginx

